module.exports = {
  content: ['./public/index.html', './src/**/*.{html,tsx,ts}'],
  outline: {
    none: 'none',
  },
  theme: {
    container: {
      center: 'true',
      padding: {
        'DEFAULT': '15px',
        'sm': '15px',
        'lg': '15px',
        'xl': '20px',
        '2xl': '25px',
      },
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1600px',
    },
    spacing: {
      sidebar: '264px',
      px: '1px',
      0: '0',
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '32px',
      8: '40px',
      9: '48px',
      10: '56px',
    },
    fontSize: {
      'sm': [
        '12px',
        {
          lineHeight: '14px',
        },
      ],
      'base': [
        '14px',
        {
          lineHeight: '20px',
        },
      ],
      'lg': [
        '16px',
        {
          lineHeight: '24px',
        },
      ],
      'xl': [
        '20px',
        {
          lineHeight: '28px',
        },
      ],
      '2xl': [
        '24px',
        {
          lineHeight: '32px',
        },
      ],
      '3xl': [
        '28px',
        {
          lineHeight: '36px',
        },
      ],
    },
    fontWeight: {
      100: '100',
      200: '200',
      300: '300',
      400: '400',
      500: '500',
      600: '600',
      700: '700',
      800: '800',
      900: '900',
    },
    lineHeight: {
      normal: '16px',
      2: '24px',
      3: '28px',
      4: '32px',
      5: '36px',
    },
    fontFamily: {
      Roboto: ['Roboto'],
      Manrope: ['Manrope', 'sans-serif'],
    },
    fill: {
      current: '#000',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: '#000',
      white: '#fff',
      sidebar: '#132340',
      primary: '#2563EB',
      secondary: '#475569',
      danger: '#DC2626',
      warning: '#F59E0B',
      success: '#0D9488',
      blue: {
        primary: '#2563EB',
        50: '#EFF6FF',
        100: '#DBEAFE',
        200: '#BFDBFE',
        300: '#93C5FD',
        400: '#60A5FA',
        500: '#60A5FA',
        600: '#2563EB',
        700: '#1E40AF',
        800: '#1E40AF',
        900: '#1E3A8A',
      },
      blueGray: {
        50: '#F8FAFC',
        100: '#F1F5F9',
        200: '#E2E8F0',
        300: '#CBD5E1',
        400: '#94A3B8',
        500: '#64748B',
        600: '#475569',
        700: '#334155',
        800: '#1E293B',
        900: '#0F172A',
      },
      coolGray: {
        50: '#F9FAFB',
        100: '#F3F4F6',
        200: '#E5E7EB',
        300: '#D1D5DB',
        400: '#9CA3AF',
        500: '#6B7280',
        600: '#4B5563',
        700: '#374151',
        800: '#1F2937',
        900: '#111827',
      },
      red: {
        primary: '#DC2626',
        50: '#FEF2F2',
        100: '#FEE2E2',
        200: '#FECACA',
        300: '#FCA5A5',
        400: '#F87171',
        500: '#EF4444',
        600: '#DC2626',
        700: '#B91C1C',
        800: '#991B1B',
        900: '#7F1D1D',
      },
      amber: {
        50: '#FFFBEB',
        100: '#FEF3C7',
        200: '#FDE68A',
        300: '#FCD34D',
        400: '#FBBF24',
        500: '#F59E0B',
        600: '#D97706',
        700: '#B45309',
        800: '#92400E',
        900: '#78350F',
      },
      teal: {
        50: '#F0FDFA',
        100: '#CCFBF1',
        200: '#99F6E4',
        300: '#5EEAD4',
        400: '#2DD4BF',
        500: '#14B8A6',
        600: '#0D9488',
        700: '#0F766E',
        800: '#115E59',
        900: '#134E4A',
      },
    },
    textColor: (theme) => theme('colors'),
    backgroundColor: (theme) => theme('colors'),
    boxShadow: {
      sm: '0 1px 2px 0',
      md: '0 0 6px -1px',
      lg: '0 10px 15px -3px',
      xl: '0 20px 25px -5px',
      input: '0 2px 8px rgba(0, 0, 0, 0.1)',
    },
    backgroundPosition: {
      'bottom': 'bottom',
      'center': 'center',
      'left': 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      'right': 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      'top': 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    minHeight: {
      0: '0',
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '32px',
      8: '40px',
      9: '48px',
      10: '56px',
      full: '100%',
      screen: '100vh',
    },
    opacity: {
      0: '0',
      10: '0.1',
      20: '0.2',
      30: '0.3',
      40: '0.4',
      50: '0.5',
      60: '0.6',
      70: '0.7',
      80: '0.8',
      90: '0.9',
      100: '1',
    },
    zIndex: {
      auto: 'auto',
      0: '0',
      5: '5',
      10: '10',
      20: '20',
      30: '30',
      40: '40',
      50: '50',
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    borderRadius: (theme) => ({
      ...theme('spacing'),
      full: '9999px',
    }),
    borderColor: (theme) => ({
      ...theme('colors'),
      default: theme('colors.blue.300', 'currentColor'),
    }),
    divideColor: (theme) => theme('borderColor'),
    divideOpacity: (theme) => theme('borderOpacity'),
    divideWidth: (theme) => theme('borderWidth'),
    cursor: {
      'auto': 'auto',
      'default': 'default',
      'pointer': 'pointer',
      'wait': 'wait',
      'text': 'text',
      'move': 'move',
      'not-allowed': 'not-allowed',
    },
    transitionProperty: {
      none: 'none',
      all: 'all',
      default:
        'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform',
      colors: 'background-color, border-color, color, fill, stroke',
      opacity: 'opacity',
      shadow: 'box-shadow',
      transform: 'transform',
    },
    transitionTimingFunction: {
      'linear': 'linear',
      'in': 'cubic-bezier(0.4, 0, 1, 1)',
      'out': 'cubic-bezier(0, 0, 0.2, 1)',
      'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    transitionDuration: {
      75: '75ms',
      100: '100ms',
      150: '150ms',
      200: '200ms',
      300: '300ms',
      500: '500ms',
      700: '700ms',
      1000: '1000ms',
    },
  },
  variants: {
    fontSize: ['hover'],
    // fontSmoothing: ['responsive'],
    // fontStyle: ['responsive'],
    opacity: ['disabled'],
    // cursor: ['responsive'],
    borderColor: ['focus-visible'],
    margin: ['responsive'],
    fill: ['hover'],
    boxShadow: ['active'],
  },
  plugins: [],
};
// prefix: '',
// important: false,
// separator: ':',
// theme: {
//   screens: {
//     sm: '640px',
//     md: '768px',
//     lg: '1024px',
//     xl: '1280px',
//   },
//   colors: {
//     transparent: 'transparent',
//     current: 'currentColor',
//
//     black: '#000',
//     white: '#fff',
//     red: {
//       100: '#fff5f5',
//       200: '#fed7d7',
//       300: '#feb2b2',
//       400: '#fc8181',
//       500: '#f56565',
//       600: '#e53e3e',
//       700: '#c53030',
//       800: '#9b2c2c',
//       900: '#742a2a',
//     },
//   },
//   spacing: {
//     px: '1px',
//     0: '0',
//     1: '0.25rem',
//     2: '0.5rem',
//     3: '0.75rem',
//     4: '1rem',
//     5: '1.25rem',
//     6: '1.5rem',
//     8: '2rem',
//     10: '2.5rem',
//     12: '3rem',
//     16: '4rem',
//     20: '5rem',
//     24: '6rem',
//     32: '8rem',
//     40: '10rem',
//     48: '12rem',
//     56: '14rem',
//     64: '16rem',
//   },
//   backgroundColor: (theme) => theme('colors'),
//   backgroundOpacity: (theme) => theme('opacity'),
//   backgroundPosition: {
//     'bottom': 'bottom',
//     'center': 'center',
//     'left': 'left',
//     'left-bottom': 'left bottom',
//     'left-top': 'left top',
//     'right': 'right',
//     'right-bottom': 'right bottom',
//     'right-top': 'right top',
//     'top': 'top',
//   },
//   backgroundSize: {
//     auto: 'auto',
//     cover: 'cover',
//     contain: 'contain',
//   },
//   borderColor: (theme) => ({
//     ...theme('colors'),
//     default: theme('colors.gray.300', 'currentColor'),
//   }),
//   borderOpacity: (theme) => theme('opacity'),
//   borderRadius: {
//     none: '0',
//     sm: '0.125rem',
//     default: '0.25rem',
//     md: '0.375rem',
//     lg: '0.5rem',
//     full: '9999px',
//   },
//   borderWidth: {
//     default: '1px',
//     0: '0',
//     2: '2px',
//     4: '4px',
//     8: '8px',
//   },
//   boxShadow: {
//     'xs': '0 0 0 1px rgba(0, 0, 0, 0.05)',
//     'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
//     'default':
//       '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
//     'md':
//       '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
//     'lg':
//       '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
//     'xl':
//       '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
//     '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
//     'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
//     'outline': '0 0 0 3px rgba(66, 153, 225, 0.5)',
//     'none': 'none',
//   },
//   container: {},
//   cursor: {
//     'auto': 'auto',
//     'default': 'default',
//     'pointer': 'pointer',
//     'wait': 'wait',
//     'text': 'text',
//     'move': 'move',
//     'not-allowed': 'not-allowed',
//   },
//   divideColor: (theme) => theme('borderColor'),
//   divideOpacity: (theme) => theme('borderOpacity'),
//   divideWidth: (theme) => theme('borderWidth'),
//   fill: {
//     current: 'currentColor',
//   },
//   flex: {
//     1: '1 1 0%',
//     auto: '1 1 auto',
//     initial: '0 1 auto',
//     none: 'none',
//   },
//   flexGrow: {
//     0: '0',
//     default: '1',
//   },
//   flexShrink: {
//     0: '0',
//     default: '1',
//   },
//   fontFamily: {
//     sans: [
//       'system-ui',
//       '-apple-system',
//       'BlinkMacSystemFont',
//       '"Segoe UI"',
//       'Roboto',
//       '"Helvetica Neue"',
//       'Arial',
//       '"Noto Sans"',
//       'sans-serif',
//       '"Apple Color Emoji"',
//       '"Segoe UI Emoji"',
//       '"Segoe UI Symbol"',
//       '"Noto Color Emoji"',
//     ],
//     serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
//     mono: [
//       'Menlo',
//       'Monaco',
//       'Consolas',
//       '"Liberation Mono"',
//       '"Courier New"',
//       'monospace',
//     ],
//   },
//   fontSize: {
//     'xs': '0.75rem',
//     'sm': '0.875rem',
//     'base': '1rem',
//     'lg': '1.125rem',
//     'xl': '1.25rem',
//     '2xl': '1.5rem',
//     '3xl': '1.875rem',
//     '4xl': '2.25rem',
//     '5xl': '3rem',
//     '6xl': '4rem',
//   },
//   fontWeight: {
//     hairline: '100',
//     thin: '200',
//     light: '300',
//     normal: '400',
//     medium: '500',
//     semibold: '600',
//     bold: '700',
//     extrabold: '800',
//     black: '900',
//   },
//   height: (theme) => ({
//     auto: 'auto',
//     ...theme('spacing'),
//     full: '100%',
//     screen: '100vh',
//   }),
//   inset: {
//     0: '0',
//     auto: 'auto',
//   },
//   letterSpacing: {
//     tighter: '-0.05em',
//     tight: '-0.025em',
//     normal: '0',
//     wide: '0.025em',
//     wider: '0.05em',
//     widest: '0.1em',
//   },
//   lineHeight: {
//     none: '1',
//     tight: '1.25',
//     snug: '1.375',
//     normal: '1.5',
//     relaxed: '1.625',
//     loose: '2',
//     3: '.75rem',
//     4: '1rem',
//     5: '1.25rem',
//     6: '1.5rem',
//     7: '1.75rem',
//     8: '2rem',
//     9: '2.25rem',
//     10: '2.5rem',
//   },
//   listStyleType: {
//     none: 'none',
//     disc: 'disc',
//     decimal: 'decimal',
//   },
//   margin: (theme, { negative }) => ({
//     auto: 'auto',
//     ...theme('spacing'),
//     ...negative(theme('spacing')),
//   }),
//   maxHeight: {
//     full: '100%',
//     screen: '100vh',
//   },
//   maxWidth: (theme, { breakpoints }) => ({
//     'none': 'none',
//     'xs': '20rem',
//     'sm': '24rem',
//     'md': '28rem',
//     'lg': '32rem',
//     'xl': '36rem',
//     '2xl': '42rem',
//     '3xl': '48rem',
//     '4xl': '56rem',
//     '5xl': '64rem',
//     '6xl': '72rem',
//     'full': '100%',
//     ...breakpoints(theme('screens')),
//   }),
//   minHeight: {
//     0: '0',
//     full: '100%',
//     screen: '100vh',
//   },
//   minWidth: {
//     0: '0',
//     full: '100%',
//   },
//   objectPosition: {
//     'bottom': 'bottom',
//     'center': 'center',
//     'left': 'left',
//     'left-bottom': 'left bottom',
//     'left-top': 'left top',
//     'right': 'right',
//     'right-bottom': 'right bottom',
//     'right-top': 'right top',
//     'top': 'top',
//   },
//   opacity: {
//     0: '0',
//     25: '0.25',
//     50: '0.5',
//     75: '0.75',
//     100: '1',
//   },
//   order: {
//     first: '-9999',
//     last: '9999',
//     none: '0',
//     1: '1',
//     2: '2',
//     3: '3',
//     4: '4',
//     5: '5',
//     6: '6',
//     7: '7',
//     8: '8',
//     9: '9',
//     10: '10',
//     11: '11',
//     12: '12',
//   },
//   padding: (theme) => theme('spacing'),
//   placeholderColor: (theme) => theme('colors'),
//   placeholderOpacity: (theme) => theme('opacity'),
//   space: (theme, { negative }) => ({
//     ...theme('spacing'),
//     ...negative(theme('spacing')),
//   }),
//   stroke: {
//     current: 'currentColor',
//   },
//   strokeWidth: {
//     0: '0',
//     1: '1',
//     2: '2',
//   },
//   textColor: (theme) => theme('colors'),
//   textOpacity: (theme) => theme('opacity'),
//   width: (theme) => ({
//     'auto': 'auto',
//     ...theme('spacing'),
//     '1/2': '50%',
//     '1/3': '33.333333%',
//     '2/3': '66.666667%',
//     '1/4': '25%',
//     '2/4': '50%',
//     '3/4': '75%',
//     '1/5': '20%',
//     '2/5': '40%',
//     '3/5': '60%',
//     '4/5': '80%',
//     '1/6': '16.666667%',
//     '2/6': '33.333333%',
//     '3/6': '50%',
//     '4/6': '66.666667%',
//     '5/6': '83.333333%',
//     '1/12': '8.333333%',
//     '2/12': '16.666667%',
//     '3/12': '25%',
//     '4/12': '33.333333%',
//     '5/12': '41.666667%',
//     '6/12': '50%',
//     '7/12': '58.333333%',
//     '8/12': '66.666667%',
//     '9/12': '75%',
//     '10/12': '83.333333%',
//     '11/12': '91.666667%',
//     'full': '100%',
//     'screen': '100vw',
//   }),
//   zIndex: {
//     auto: 'auto',
//     0: '0',
//     10: '10',
//     20: '20',
//     30: '30',
//     40: '40',
//     50: '50',
//   },
//   gap: (theme) => theme('spacing'),
//   gridTemplateColumns: {
//     none: 'none',
//     1: 'repeat(1, minmax(0, 1fr))',
//     2: 'repeat(2, minmax(0, 1fr))',
//     3: 'repeat(3, minmax(0, 1fr))',
//     4: 'repeat(4, minmax(0, 1fr))',
//     5: 'repeat(5, minmax(0, 1fr))',
//     6: 'repeat(6, minmax(0, 1fr))',
//     7: 'repeat(7, minmax(0, 1fr))',
//     8: 'repeat(8, minmax(0, 1fr))',
//     9: 'repeat(9, minmax(0, 1fr))',
//     10: 'repeat(10, minmax(0, 1fr))',
//     11: 'repeat(11, minmax(0, 1fr))',
//     12: 'repeat(12, minmax(0, 1fr))',
//   },
//   gridColumn: {
//     'auto': 'auto',
//     'span-1': 'span 1 / span 1',
//     'span-2': 'span 2 / span 2',
//     'span-3': 'span 3 / span 3',
//     'span-4': 'span 4 / span 4',
//     'span-5': 'span 5 / span 5',
//     'span-6': 'span 6 / span 6',
//     'span-7': 'span 7 / span 7',
//     'span-8': 'span 8 / span 8',
//     'span-9': 'span 9 / span 9',
//     'span-10': 'span 10 / span 10',
//     'span-11': 'span 11 / span 11',
//     'span-12': 'span 12 / span 12',
//   },
//   gridColumnStart: {
//     auto: 'auto',
//     1: '1',
//     2: '2',
//     3: '3',
//     4: '4',
//     5: '5',
//     6: '6',
//     7: '7',
//     8: '8',
//     9: '9',
//     10: '10',
//     11: '11',
//     12: '12',
//     13: '13',
//   },
//   gridColumnEnd: {
//     auto: 'auto',
//     1: '1',
//     2: '2',
//     3: '3',
//     4: '4',
//     5: '5',
//     6: '6',
//     7: '7',
//     8: '8',
//     9: '9',
//     10: '10',
//     11: '11',
//     12: '12',
//     13: '13',
//   },
//   gridTemplateRows: {
//     none: 'none',
//     1: 'repeat(1, minmax(0, 1fr))',
//     2: 'repeat(2, minmax(0, 1fr))',
//     3: 'repeat(3, minmax(0, 1fr))',
//     4: 'repeat(4, minmax(0, 1fr))',
//     5: 'repeat(5, minmax(0, 1fr))',
//     6: 'repeat(6, minmax(0, 1fr))',
//   },
//   gridRow: {
//     'auto': 'auto',
//     'span-1': 'span 1 / span 1',
//     'span-2': 'span 2 / span 2',
//     'span-3': 'span 3 / span 3',
//     'span-4': 'span 4 / span 4',
//     'span-5': 'span 5 / span 5',
//     'span-6': 'span 6 / span 6',
//   },
//   gridRowStart: {
//     auto: 'auto',
//     1: '1',
//     2: '2',
//     3: '3',
//     4: '4',
//     5: '5',
//     6: '6',
//     7: '7',
//   },
//   gridRowEnd: {
//     auto: 'auto',
//     1: '1',
//     2: '2',
//     3: '3',
//     4: '4',
//     5: '5',
//     6: '6',
//     7: '7',
//   },
//   transformOrigin: {
//     'center': 'center',
//     'top': 'top',
//     'top-right': 'top right',
//     'right': 'right',
//     'bottom-right': 'bottom right',
//     'bottom': 'bottom',
//     'bottom-left': 'bottom left',
//     'left': 'left',
//     'top-left': 'top left',
//   },
//   scale: {
//     0: '0',
//     50: '.5',
//     75: '.75',
//     90: '.9',
//     95: '.95',
//     100: '1',
//     105: '1.05',
//     110: '1.1',
//     125: '1.25',
//     150: '1.5',
//   },
//   rotate: {
//     '-180': '-180deg',
//     '-90': '-90deg',
//     '-45': '-45deg',
//     '0': '0',
//     '45': '45deg',
//     '90': '90deg',
//     '180': '180deg',
//   },
//   translate: (theme, { negative }) => ({
//     ...theme('spacing'),
//     ...negative(theme('spacing')),
//     '-full': '-100%',
//     '-1/2': '-50%',
//     '1/2': '50%',
//     'full': '100%',
//   }),
//   skew: {
//     '-12': '-12deg',
//     '-6': '-6deg',
//     '-3': '-3deg',
//     '0': '0',
//     '3': '3deg',
//     '6': '6deg',
//     '12': '12deg',
//   },
//   transitionProperty: {
//     none: 'none',
//     all: 'all',
//     default:
//       'background-color, border-color, color, fill, stroke, opacity, box-shadow, transform',
//     colors: 'background-color, border-color, color, fill, stroke',
//     opacity: 'opacity',
//     shadow: 'box-shadow',
//     transform: 'transform',
//   },
//   transitionTimingFunction: {
//     'linear': 'linear',
//     'in': 'cubic-bezier(0.4, 0, 1, 1)',
//     'out': 'cubic-bezier(0, 0, 0.2, 1)',
//     'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
//   },
//   transitionDuration: {
//     75: '75ms',
//     100: '100ms',
//     150: '150ms',
//     200: '200ms',
//     300: '300ms',
//     500: '500ms',
//     700: '700ms',
//     1000: '1000ms',
//   },
//   transitionDelay: {
//     75: '75ms',
//     100: '100ms',
//     150: '150ms',
//     200: '200ms',
//     300: '300ms',
//     500: '500ms',
//     700: '700ms',
//     1000: '1000ms',
//   },
// },
// variants: {
//   accessibility: ['responsive', 'focus'],
//   alignContent: ['responsive'],
//   alignItems: ['responsive'],
//   alignSelf: ['responsive'],
//   appearance: ['responsive'],
//   backgroundAttachment: ['responsive'],
//   backgroundColor: ['responsive', 'hover', 'focus'],
//   backgroundOpacity: ['responsive', 'hover', 'focus'],
//   backgroundPosition: ['responsive'],
//   backgroundRepeat: ['responsive'],
//   backgroundSize: ['responsive'],
//   borderCollapse: ['responsive'],
//   borderColor: ['responsive', 'hover', 'focus'],
//   borderOpacity: ['responsive', 'hover', 'focus'],
//   borderRadius: ['responsive'],
//   borderStyle: ['responsive'],
//   borderWidth: ['responsive'],
//   boxShadow: ['responsive', 'hover', 'focus'],
//   boxSizing: ['responsive'],
//   cursor: ['responsive'],
//   display: ['responsive'],
//   divideColor: ['responsive'],
//   divideOpacity: ['responsive'],
//   divideWidth: ['responsive'],
//   fill: ['responsive'],
//   flex: ['responsive'],
//   flexDirection: ['responsive'],
//   flexGrow: ['responsive'],
//   flexShrink: ['responsive'],
//   flexWrap: ['responsive'],
//   float: ['responsive'],
//   clear: ['responsive'],
//   fontFamily: ['responsive'],
//   fontSize: ['responsive'],
//   fontSmoothing: ['responsive'],
//   fontStyle: ['responsive'],
//   fontWeight: ['responsive', 'hover', 'focus'],
//   height: ['responsive'],
//   inset: ['responsive'],
//   justifyContent: ['responsive'],
//   letterSpacing: ['responsive'],
//   lineHeight: ['responsive'],
//   listStylePosition: ['responsive'],
//   listStyleType: ['responsive'],
//   margin: ['responsive'],
//   maxHeight: ['responsive'],
//   maxWidth: ['responsive'],
//   minHeight: ['responsive'],
//   minWidth: ['responsive'],
//   objectFit: ['responsive'],
//   objectPosition: ['responsive'],
//   opacity: ['responsive', 'hover', 'focus'],
//   order: ['responsive'],
//   outline: ['responsive', 'focus'],
//   overflow: ['responsive'],
//   padding: ['responsive'],
//   placeholderColor: ['responsive', 'focus'],
//   placeholderOpacity: ['responsive', 'focus'],
//   pointerEvents: ['responsive'],
//   position: ['responsive'],
//   resize: ['responsive'],
//   space: ['responsive'],
//   stroke: ['responsive'],
//   strokeWidth: ['responsive'],
//   tableLayout: ['responsive'],
//   textAlign: ['responsive'],
//   textColor: ['responsive', 'hover', 'focus'],
//   textOpacity: ['responsive', 'hover', 'focus'],
//   textDecoration: ['responsive', 'hover', 'focus'],
//   textTransform: ['responsive'],
//   userSelect: ['responsive'],
//   verticalAlign: ['responsive'],
//   visibility: ['responsive'],
//   whitespace: ['responsive'],
//   width: ['responsive'],
//   wordBreak: ['responsive'],
//   zIndex: ['responsive'],
//   gap: ['responsive'],
//   gridAutoFlow: ['responsive'],
//   gridTemplateColumns: ['responsive'],
//   gridColumn: ['responsive'],
//   gridColumnStart: ['responsive'],
//   gridColumnEnd: ['responsive'],
//   gridTemplateRows: ['responsive'],
//   gridRow: ['responsive'],
//   gridRowStart: ['responsive'],
//   gridRowEnd: ['responsive'],
//   transform: ['responsive'],
//   transformOrigin: ['responsive'],
//   scale: ['responsive', 'hover', 'focus'],
//   rotate: ['responsive', 'hover', 'focus'],
//   translate: ['responsive', 'hover', 'focus'],
//   skew: ['responsive', 'hover', 'focus'],
//   transitionProperty: ['responsive'],
//   transitionTimingFunction: ['responsive'],
//   transitionDuration: ['responsive'],
//   transitionDelay: ['responsive'],
// },
// corePlugins: {},
