export const executors = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  WS_OPEN: 'WS_OPEN',
  WS_CLOSE: 'WS_CLOSE',
  WS_CONNECTING: 'WS_CONNECTING',
  WS_ERROR: 'WS_ERROR',
  WS_MESSAGE: 'WS_MESSAGE',
} as const;

export const watchers = {
  INCREMENT: 'INCREMENT_WATCHER',
  DECREMENT: 'DECREMENT_WATCHER',
  INCREMENT_ASYNC: 'INCREMENT_ASYNC_WATCHER',
  DECREMENT_ASYNC: 'DECREMENT_ASYNC_WATCHER',
  CANCEL_ASYNC: 'CANCEL_ASYNC',

  WS_CONNECT_REQUEST: 'WS_CONNECT_REQUEST',
  WS_SEND_REQUEST: 'WS_SEND_REQUEST',
  WS_CLOSE_REQUEST: 'WS_CLOSE_REQUEST',
  WS_CLOSE_WATCHER: 'WS_CLOSE_WATCHER',
  WS_OPEN_WATCHER: 'WS_OPEN_WATCHER',
  WS_ERROR_WATCHER: 'WS_ERROR_WATCHER',
  WS_MESSAGE_WATCHER: 'WS_MESSAGE_WATCHER',
} as const;
